sonar.projectKey=tothkarolydavid_dietinator
sonar.organization=tothkarolydavid
sonar.projectName=Dietinator
sonar.sources=src,app,components
sonar.exclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/__mocks__/**,coverage/**,dist/**,android/**,.expo/**,node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
